[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"

# React Router redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Jika tidak pakai functions, comment atau hapus section ini
# [functions]
#   directory = ".netlify/functions"